### ISSUE TITLE
Error "java.lang.IllegalArgumentException: URI is not absolute“ when 'cf push' resource server

### ISSUE THREAD

**Issue by David-VMware** [pivotal-cf/identity-sample-apps#2]
Hi,

I got the following error when run 'cf push' resource server. Could you help check?

`2016-10-12T01:32:37.65+0000 [APP/0]      OUT org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire method: public void org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.setFilterChainProxySecurityConfigurer(org.springframework.security.config.annotation.ObjectPostProcessor,java.util.List) throws java.lang.Exception; nested exception is org.springframework.beans.factory.BeanExpressionException: Expression parsing failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.springframework.security.oauth2.provider.token.TokenStore org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfiguration.tokenStore; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtTokenStore' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.TokenStore]: Factory method 'jwtTokenStore' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtTokenEnhancer' defined in class path resource [org/springframework/boot/autoconfigure/security/oauth2/resource/ResourceServerTokenServicesConfiguration$JwtTokenServicesConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter]: Factory method 'jwtTokenEnhancer' threw exception; nested exception is java.lang.IllegalArgumentException: URI is not absolute
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:368) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1060) ~[spring-context-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.web.filter.DelegatingFilterProxy.initDelegate(DelegatingFilterProxy.java:326) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.web.filter.DelegatingFilterProxy.initFilterBean(DelegatingFilterProxy.java:235) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:199) ~[spring-web-4.2.6.RELEASE.jar!/:4.2.6.RELEASE]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:109) ~[tomcat-embed-core-8.0.33.jar!/:8.0.33]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4658) [tomcat-embed-core-8.0.33.jar!/:8.0.33]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5277) [tomcat-embed-core-8.0.33.jar!/:8.0.33]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat-embed-core-8.0.33.jar!/:8.0.33]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.33.jar!/:8.0.33]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.33.jar!/:8.0.33]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_71-]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_71-]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_71-]
2016-10-12T01:32:37.65+0000 [APP/0]      OUT    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71-]`

**Comment by David-VMware** [comment]
The whole log files can be found here:
[resource_server.txt](https://github.com/pivotal-cf/identity-sample-apps/files/523420/resource_server.txt)

**Comment by tnwang** [comment]
This error typically happens when the SSO Domain URL is not being set. This happens if the SSO service has not been bound to the sample application, which always happen on the first start-up if a service instance is not specified as part of the application manifest. 

Once SSO is bound to the application, the SSO Domain URL is automatically configured by the SSO Connector for Spring Boot, and this error will go away.

**Comment by satayeet** [comment]
What is SSO. I mean what is it full form?

**Comment by ppavankumar** [comment]
SSO -> Single Sign On
